-- ════════════════════════════════════════════════════════════════
-- LAL DIVANE SUPABASE SCHEMA MIGRATION
-- Run this in your Supabase SQL Editor
-- ════════════════════════════════════════════════════════════════

-- Enable UUID extension if not enabled (usually is by default in Supabase)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ════════════════════════════
-- 1. PROFILES & TRIGGER
-- ════════════════════════════
-- This links directly to Supabase's auth.users
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,
  avatar_url TEXT,
  bio TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policies for profiles
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Trigger to automatically create a profile when a new user signs up via Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, display_name, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Don't throw error if trigger exists
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
-- ════════════════════════════
-- 1.5 ALBUMS
-- ════════════════════════════
CREATE TABLE IF NOT EXISTS public.albums (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  artist TEXT DEFAULT 'Lal Divane',
  description TEXT,
  cover_url TEXT,
  release_date DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.albums ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Albums are viewable by everyone" ON public.albums FOR SELECT USING (true);


-- ════════════════════════════
-- 2. TRACKS
-- ════════════════════════════
CREATE TABLE IF NOT EXISTS public.tracks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  artist TEXT DEFAULT 'Lal Divane',
  album_id BIGINT REFERENCES public.albums(id) ON DELETE SET NULL,
  duration_seconds INTEGER NOT NULL DEFAULT 0,
  audio_url TEXT,
  cover_url TEXT,
  lyrics TEXT,
  play_count INTEGER DEFAULT 0,
  like_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.tracks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tracks are viewable by everyone" ON public.tracks FOR SELECT USING (true);
CREATE POLICY "Only authenticated users can update (e.g. play counts)" ON public.tracks FOR UPDATE USING (auth.role() = 'authenticated');
-- Only admin/service role should be able to insert/delete tracks realistically, but keeping it open for dev for now
CREATE POLICY "Service role can insert" ON public.tracks FOR INSERT WITH CHECK (auth.role() = 'authenticated');


-- ════════════════════════════
-- 3. FAVORITES
-- ════════════════════════════
CREATE TABLE IF NOT EXISTS public.favorites (
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  track_id BIGINT REFERENCES public.tracks(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (user_id, track_id)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Favorites viewable by everyone" ON public.favorites FOR SELECT USING (true);
CREATE POLICY "Users can insert their own favorites" ON public.favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own favorites" ON public.favorites FOR DELETE USING (auth.uid() = user_id);


-- ════════════════════════════
-- 4. LISTENING ACTIVITY
-- ════════════════════════════
CREATE TABLE IF NOT EXISTS public.listening_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  track_id BIGINT REFERENCES public.tracks(id) ON DELETE CASCADE NOT NULL,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE
);

ALTER TABLE public.listening_activity ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Listening activity viewable by everyone" ON public.listening_activity FOR SELECT USING (true);
CREATE POLICY "Users can insert own activity" ON public.listening_activity FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own activity" ON public.listening_activity FOR UPDATE USING (auth.uid() = user_id);


-- ════════════════════════════
-- 5. COMMUNITIES & POSTS
-- ════════════════════════════
CREATE TABLE IF NOT EXISTS public.communities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  cover_url TEXT,
  member_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.communities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Communities viewable by everyone" ON public.communities FOR SELECT USING (true);

CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT REFERENCES public.communities(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  like_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Posts viewable by everyone" ON public.posts FOR SELECT USING (true);
CREATE POLICY "Users can insert own posts" ON public.posts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own posts" ON public.posts FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own posts" ON public.posts FOR DELETE USING (auth.uid() = user_id);


-- ════════════════════════════
-- 6. TRIGGERS FOR COUNTERS
-- ════════════════════════════

-- Trigger for play_count
CREATE OR REPLACE FUNCTION public.handle_play_count()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.tracks SET play_count = play_count + 1 WHERE id = NEW.track_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_track_played ON public.listening_activity;
CREATE TRIGGER on_track_played
  AFTER INSERT ON public.listening_activity
  FOR EACH ROW EXECUTE FUNCTION public.handle_play_count();

-- Trigger for like_count
CREATE OR REPLACE FUNCTION public.handle_like_count()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.tracks SET like_count = like_count + 1 WHERE id = NEW.track_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.tracks SET like_count = like_count - 1 WHERE id = OLD.track_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_track_liked ON public.favorites;
CREATE TRIGGER on_track_liked
  AFTER INSERT OR DELETE ON public.favorites
  FOR EACH ROW EXECUTE FUNCTION public.handle_like_count();
-- ════════════════════════════
-- SEED DATA (REAL TRACKS)
-- ════════════════════════════
INSERT INTO public.tracks (title, artist, duration_seconds, cover_url, audio_url, play_count, like_count) VALUES
('Cehennem', 'Lal Divane', 215, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Cehennem%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Cehennem%20(Official%20Music).mp3', 3411, 890),
('Duyuyor musun', 'Lal Divane', 242, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Duyuyor%20Musun_%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Duyuyor%20musun%20(Official%20Music).mp3', 9387, 2340),
('Hapishane', 'Lal Divane', 198, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Hapishane%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Hapishane%20(Official%20Music).mp3', 7204, 1800),
('Hatalarım Deneyim', 'Lal Divane', 225, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Hatalar%C4%B1m%20Deneyim%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Hatalar%C4%B1m%20Deneyim%20(Official%20Music).mp3', 5981, 1540),
('Hipnotize', 'Lal Divane', 256, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Hipnotize%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Hipnotize%20(Official%20Music).mp3', 3300, 920),
('Huzursuzum', 'Lal Divane', 287, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Huzursuzum%20(Cover%20Art).png', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Huzursuzum%20(Official%20Audio).mp3', 2100, 560),
('Korkmuyorum', 'Lal Divane', 312, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Korkmuyorum%20Manip%C3%BClasyonlar%C4%B1ndan%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Korkmuyorum%20Manip%C3%BClasyonlar%C4%B1ndan%20(Official%20Music).mp3', 6520, 1120),
('Okyanuslar Yuttu Beni', 'Lal Divane', 263, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Okyanuslar%20Yuttu%20Beni%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Okyanuslar%20Yuttu%20Beni%20(Official%20Music).mp3', 6100, 1680),
('Sana Yanık', 'Lal Divane', 234, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Sana%20Yan%C4%B1k%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Sana%20Yan%C4%B1k%20(Official%20Music).mp3', 4200, 1200),
('Senin Adın', 'Lal Divane', 210, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Senin%20Ad%C4%B1n%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Senin%20ad%C4%B1n%20(Official%20Music).mp3', 3800, 950),
('Yaram Aşırı Derin', 'Lal Divane', 245, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Yaram%20A%C5%9F%C4%B1r%C4%B1%20Derin%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Yaram%20A%C5%9F%C4%B1r%C4%B1%20Derin%20(Official%20Music).mp3', 5600, 1400),
('Yarım Kalan Rüya', 'Lal Divane', 280, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Rituals%20of%20the%20Digital%20Void.jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Yar%C4%B1m%20Kalan%20R%C3%BCya%20(Official%20Audio).mp3', 2900, 780),
('Yüksek Yüksek Tepelere', 'Lal Divane', 305, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Y%C3%BCksek%20Y%C3%BCksek%20Tepelere%20(Cover%20Art).png', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Yuksek%20yuksek%20Tepelere.mp3', 7500, 1900)
ON CONFLICT DO NOTHING;

INSERT INTO public.communities (name, slug, description, member_count) VALUES
('Lyrics & Poetry', 'lyrics-poetry', 'Lal Divane şarkı sözlerindeki gizli anlamları tartış', 2341),
('Dark Aesthetics', 'dark-aesthetics', 'Lal Divane esinli sanat ve tarzını paylaş', 1808),
('Live Sessions', 'live-sessions', 'Canlı void oturumları için duyurular', 956)
ON CONFLICT (slug) DO NOTHING;
