-- ════════════════════════════════════════════════════════════════
-- LAL DIVANE - COMPREHENSIVE REPAIR & SYNC SCRIPT
-- This script fixes missing tables and populates real tracks/albums.
-- ════════════════════════════════════════════════════════════════

-- 1. Ensure ALBUMS table exists
CREATE TABLE IF NOT EXISTS public.albums (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  artist TEXT DEFAULT 'Lal Divane',
  description TEXT,
  cover_url TEXT,
  release_date DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.albums ENABLE ROW LEVEL SECURITY;

-- Add select policy if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Albums are viewable by everyone') THEN
        CREATE POLICY "Albums are viewable by everyone" ON public.albums FOR SELECT USING (true);
    END IF;
END
$$;

-- 2. Ensure TRACKS table has album_id
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS album_id BIGINT REFERENCES public.albums(id) ON DELETE SET NULL;

-- 3. Clear existing data to prevent ID conflicts (Identity Restart)
TRUNCATE public.favorites CASCADE;
TRUNCATE public.listening_activity CASCADE;
TRUNCATE public.tracks RESTART IDENTITY CASCADE;
TRUNCATE public.albums RESTART IDENTITY CASCADE;

-- 4. Insert Albums
INSERT INTO public.albums (title, artist, description, cover_url, release_date) VALUES
('Rituals of the Digital Void', 'Lal Divane', 'A journey through the static and echoes of the infinite digital abyss.', 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Rituals%20of%20the%20Digital%20Void.jpg', '2024-03-08'),
('Single Collection', 'Lal Divane', 'Echos released as individual manifests.', '/lal-divane-avatar.png', '2024-01-01');

-- 5. Insert Tracks (linked to albums)
-- Single Collection (album_id: 2)
INSERT INTO public.tracks (title, artist, album_id, duration_seconds, cover_url, audio_url, play_count, like_count) VALUES
('Cehennem', 'Lal Divane', 2, 215, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Cehennem%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Cehennem%20(Official%20Music).mp3', 3411, 890),
('Duyuyor musun', 'Lal Divane', 2, 242, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Duyuyor%20Musun_%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Duyuyor%20musun%20(Official%20Music).mp3', 9387, 2340),
('Hapishane', 'Lal Divane', 2, 198, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Hapishane%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Hapishane%20(Official%20Music).mp3', 7204, 1800),
('Hatalarım Deneyim', 'Lal Divane', 2, 225, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Hatalar%C4%B1m%20Deneyim%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Hatalar%C4%B1m%20Deneyim%20(Official%20Music).mp3', 5981, 1540),
('Hipnotize', 'Lal Divane', 2, 256, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Hipnotize%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Hipnotize%20(Official%20Music).mp3', 3300, 920),
('Huzursuzum', 'Lal Divane', 2, 287, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Huzursuzum%20(Cover%20Art).png', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Huzursuzum%20(Official%20Audio).mp3', 2100, 560),
('Korkmuyorum', 'Lal Divane', 2, 312, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Korkmuyorum%20Manip%C3%BClasyonlar%C4%B1ndan%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Korkmuyorum%20Manip%C3%BClasyonlar%C4%B1ndan%20(Official%20Music).mp3', 6520, 1120),
('Okyanuslar Yuttu Beni', 'Lal Divane', 2, 263, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Okyanuslar%20Yuttu%20Beni%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Okyanuslar%20Yuttu%20Beni%20(Official%20Music).mp3', 6100, 1680),
('Sana Yanık', 'Lal Divane', 2, 234, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Sana%20Yan%C4%B1k%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Sana%20Yan%C4%B1k%20(Official%20Music).mp3', 4200, 1200),
('Senin Adın', 'Lal Divane', 2, 210, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Senin%20Ad%C4%B1n%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Senin%20ad%C4%B1n%20(Official%20Music).mp3', 3800, 950),
('Yaram Aşırı Derin', 'Lal Divane', 2, 245, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Yaram%20A%C5%9F%C4%B1r%C4%B1%20Derin%20(Cover%20Art).jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Yaram%20A%C5%9F%C4%B1r%C4%B1%20Derin%20(Official%20Music).mp3', 5600, 1400),
('Yarım Kalan Rüya', 'Lal Divane', 2, 280, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Rituals%20of%20the%20Digital%20Void.jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Yar%C4%B1m%20Kalan%20R%C3%BCya%20(Official%20Audio).mp3', 2900, 780),
('Yüksek Yüksek Tepelere', 'Lal Divane', 2, 305, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Y%C3%BCksek%20Y%C3%BCksek%20Tepelere%20(Cover%20Art).png', 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Yuksek%20yuksek%20Tepelere.mp3', 7500, 1900);

-- Rituals of the Digital Void (album_id: 1)
INSERT INTO public.tracks (title, artist, album_id, duration_seconds, cover_url, audio_url, play_count, like_count) VALUES
('Archive of the Unsaid', 'Lal Divane', 1, 312, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Rituals%20of%20the%20Digital%20Void.jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/ROFDV/%E2%80%9CArchive%20of%20the%20Unsaid%E2%80%9D.mp3', 420, 120),
('Blackburn Signal', 'Lal Divane', 1, 285, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Rituals%20of%20the%20Digital%20Void.jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/ROFDV/%E2%80%9CBlackburn%20Signal%E2%80%9D.mp3', 380, 95),
('Ritual Without End', 'Lal Divane', 1, 345, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Rituals%20of%20the%20Digital%20Void.jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/ROFDV/%E2%80%9CRitual%20Without%20End%E2%80%9D.mp3', 560, 140),
('Transmission Not Meant', 'Lal Divane', 1, 298, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Rituals%20of%20the%20Digital%20Void.jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/ROFDV/%E2%80%9CTransmission%20Not%20Meant%E2%80%9D.mp3', 290, 78),
('VOID RADIO CORE', 'Lal Divane', 1, 420, 'https://raw.githubusercontent.com/laldivane/Tracks/main/CoverArts/Lal%20Divane%20-%20Rituals%20of%20the%20Digital%20Void.jpg', 'https://raw.githubusercontent.com/laldivane/Tracks/main/ROFDV/%E2%80%9CVOID%20RADIO%20CORE%E2%80%9D.mp3', 750, 190);
